ErrorLogging:
  image: kbase/errorlogging
  environment:
    USER_TOKEN: ${USER_TOKEN}
    SERVICE_WIZARD_URL: ${SERVICE_WIZARD_URL}
    ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
    ERROR_DUMP: ${ERROR_DUMP}